name: Get YouTube Live m3u8
on:
  schedule:
    - cron: "0 */5 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install yt-dlp
      run: |
        sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
        sudo chmod a+rx /usr/local/bin/yt-dlp

    - name: Get ctitv.m3u8
      run: |
        touch ./ctitv.m3u8
        sudo cat >./ctitv.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/c/ctitv/live)
        EOL
    - name: Get ttvnews.m3u8
      run: |
        touch ./ttvnews.m3u8
        sudo cat >./ttvnews.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=xL0ch83RAK8)
        EOL
    - name: Get ftvnews.m3u8
      run: |
        touch ./ftvnews.m3u8
        sudo cat >./ftvnews.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/c/FTVLIVE/live)
        EOL
    - name: Get ctsnews.m3u8
      run: |
        touch ./ctsnews.m3u8
        sudo cat >./ctsnews.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/c/CtsTw/live)
        EOL
    - name: Get ctvnews.m3u8
      run: |
        touch ./ctvnews.m3u8
        sudo cat >./ctvnews.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/c/twctvnews/live)
        EOL
    - name: Get setlive.m3u8
      run: |
        touch ./setlive.m3u8
        sudo cat >./setlive.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=FoBfXvlOR6I)
        EOL
    - name: Get setinews.m3u8
      run: |
        touch ./setinews.m3u8
        sudo cat >./setinews.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/c/setmoney159/live)
        EOL
    - name: Get ebcnews.m3u8
      run: |
        touch ./ebcnews.m3u8
        sudo cat >./ebcnews.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=R2iMq5LKXco)
        EOL
    - name: Get hyxw.m3u8
      run: |
        touch ./hyxw.m3u8
        sudo cat >./hyxw.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/c/寰宇新聞頻道/live)
        EOL
    - name: Get tvbs.m3u8
      run: |
        touch ./tvbs.m3u8
        sudo cat >./tvbs.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/c/TVBSNEWS01/live)
        EOL
    - name: Get tvbsnews.m3u8
      run: |
        touch ./tvbsnews.m3u8
        sudo cat >./tvbsnews.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=2mCSYvcfhtc)
        EOL
    - name: Get dscj.m3u8
      run: |
        touch ./dscj.m3u8
        sudo cat >./dscj.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=ABn_ccXn_jc)
        EOL
    - name: Get ctsshow.m3u8
      run: |
        touch ./ctsshow.m3u8
        sudo cat >./ctsshow.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/c/TBSCTSSHOW/live)
        EOL
    - name: Get ctinews.m3u8
      run: |
        touch ./ctinews.m3u8
        sudo cat >./ctinews.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=_QbRXRnHMVY)
        EOL
    - name: Get tvbszh.m3u8
      run: |
        touch ./tvbszh.m3u8
        sudo cat >./tvbszh.m3u8 <<EOL
        $(youtube-dl -g https://www.youtube.com/watch?v=YvdcZ_jpLXE)
        EOL
    - name : Upload artifact
      uses: actions/upload-artifact@master
      with:
        name: YTlive m3u8
        path: .
    - name: Git push assets to "YTlive" branch
      run: |
        git init
        git config --local user.name "actions"
        git config --local user.email "action@github.com"
        git checkout -b YTlive
        git add .
        git commit -m "Update YTlive"
        git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        git push -f -u origin YTlive
